name: Test

on:
  schedule:
    - cron: 0 23 * * 4
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest
   
    steps:

      - name: Checkout
        uses: actions/checkout@main
       
      - name: Upload release asset
        #if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPTOKEN }}
          file: *
          tag: ${{ github.ref }}
          file_glob: true
